[tools]
bun = "latest"
node = "latest"

[env]
_ = { path = "./node_modules/.bin" }

[tasks]
format = { run = "oxfmt && treefmt" }

[deps]
bun = { auto = true }

[settings]
dotfiles = { root = "dotfiles", default_mode = "symlink" }

[dotfiles]
"~/.config/ghostty" = { source = "dotfiles/ghostty/.config/ghostty" }
