// THIS FILE IS GENERATED BY scripts/bun/sync-format-ignore.ts
// If you want to change any options edit:
//   scripts/bun/format-ignore-templates/oxfmt.config.ts
import { defineConfig } from "oxfmt";

export default defineConfig({
  ignorePatterns: [
    ".DS_Store",
    "*.lock",
    "*.lockb",
    "dotfiles/pi/.pi/agent/auth.json",
    "dotfiles/pi/.pi/agent/bin/",
    "dotfiles/pi/.pi/agent/cache/",
    "dotfiles/pi/.pi/agent/intercom/*.pid",
    "dotfiles/pi/.pi/agent/intercom/*.sock",
    "dotfiles/pi/.pi/agent/run-history.jsonl",
    "dotfiles/pi/.pi/agent/sessions/",
    "dotfiles/pi/.pi/pi-acp/",
    "dotfiles/pi/.pi/pi-extensions/pi-hashline-readmap",
    "dotfiles/pi/.pi/pi-extensions/pi-plannotator/source",
    "dotfiles/pi/.pi/pi-extensions/pi-prompt-template-model",
    "dotfiles/pi/.pi/pi-extensions/pi-subagents",
    "dotfiles/pi/.pi/pi-extensions/pi-web-access",
    "dotfiles/pi/.pi/pi-extensions/slop-review",
    "dotfiles/pi/.pi/pi-extensions/tmustier-pi-extensions",
    "dotfiles/zed/.config/zed/*",
    "!dotfiles/zed/.config/zed/keymap.json",
    "!dotfiles/zed/.config/zed/settings.json",
    "node_modules/",
    "tmp",
  ],
});
