// THIS FILE IS GENERATED BY scripts/bun/sync-format-ignore.ts
// If you want to change any options edit:
//   scripts/bun/format-ignore-templates/oxfmt.config.ts
import { defineConfig } from "oxfmt";

export default defineConfig({
  ignorePatterns: [
    // $MARKER$
  ],
});
